### ISSUE TITLE
Property name typo

### ISSUE THREAD

**Issue by codemusings** [datanucleus/docs-datanucleus#1]
Hey Andy,

I think there are some typos in the section for dynamically generating a persistence unit:

http://www.datanucleus.org:15080/products/accessplatform_5_2/jdo/persistence.html#persistenceunit

Under the heading "Dynamically generated Persistence-Unit" the example uses properties that start with `javax.jdo`. I believe it should be `javax.jdo.option`. If you can point out the relevant file. I could submit a patch.

**Comment by andyjefferson** [comment]
You're correct. 
The project for the actual docs is "docs-accessplatform". This project you raised on is the "datanucleus.org" top level docs only. Raise the Pull Request against that, thx
